# .github/workflows/analysis.yml
name: "Static analysis"

on: [ push ]

jobs:

    build:
        name:    "PHPStan"
        runs-on: ubuntu-22.04

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v3

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "7.1"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  |
                      php --version
                      composer --version
                      COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Application"
                run:  vendor/bin/phpstan --version

            -   name: "Analyses"
                run:  vendor/bin/phpstan analyse src/ --error-format=github
